django_tutorial/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('leaderline/', views.leaderline, name='leader line testing'),
    path('gojs/', views.gojs, name='GoJS Concept Map testing')
]

polls/models.py
import datetime

from django.db import models
from django.utils import timezone
# Create your models here.

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

    def __str__(self):
        return self.question_text

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

polls/views.py
# Long method
# from django.shortcuts import render
from django.http import HttpResponse
# from django.template import loader

# Shortcut method
from django.shortcuts import render, get_object_or_404

from django.http import Http404

from .models import Question

# Create your views here.


def index(request):
    # questions = {"question1": "What is your name?", "question2": "What is your favorite color?"}

    # return HttpResponse(json.dumps(questions))
    # return HttpResponse("Hello, world. You're at the polls index page.")

    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    # template = loader.get_template('polls/index.html')
    context = {
        'latest_question_list': latest_question_list
    }

    return render(request, 'polls/index.html', context)

    # return HttpResponse(template.render(context, request))


def detail(request, question_id):
    # try:
    #     question = Question.objects.get(pk=question_id)
    # except Question.DoesNotExist:
    #     raise Http404("Question does not exist")

    # return render(request, 'polls/detail.html', {'question': question})
    # return HttpResponse(f"You're looking at question {question_id}.")

    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/detail.html', {'question': question})


def results(request, question_id):
    return HttpResponse(f"You're looking at the results of question {question_id}.")


def vote(request, question_id):
    return HttpResponse(f"You're voting on question {question_id}.")

def leaderline(request):
    return render(request, 'polls/leaderline.html', {})

def gojs(request):
    return render(request, 'polls/conceptMap.html', {})

polls/templates/polls/conceptMap.html
<!DOCTYPE html>
<html lang="en">

{% load static %}

<body>
  <div id="allSampleContent" class="p-4 w-full">

    <div id="myDiagramDiv"
      style="background-color: whitesmoke; border: 1px solid black; width: 100%; height: 700px; position: relative; -webkit-tap-highlight-color: rgba(255, 255, 255, 0);">
      <canvas tabindex="0" width="1035" height="681"
        style="position: absolute; top: 0px; left: 0px; z-index: 2; user-select: none; touch-action: none; width: 1035px; height: 681px;">This
        text is displayed if your browser does not support the Canvas HTML element.</canvas>
      <div style="position: absolute; overflow: auto; width: 1035px; height: 698px; z-index: 1;">
        <div style="position: absolute; width: 1054px; height: 1px;"></div>
      </div>
    </div>

    <div id="reactEntry">Loading React...</div>

</body>

<script src="https://unpkg.com/gojs@2.2.20/release/go.js"></script>
<script src="{% static 'js/concept-map.js' %}"></script>
<script type="text/javascript" src="{% static 'js/bundle.js' %}"></script>

</html>

polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>
<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }}</li>
{% endfor %}
</ul>

polls/templates/polls/index.html
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

polls/templates/polls/leaderline.html
<!DOCTYPE html>
<html lang="en">

{% load static %}

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <title>Document</title>
</head>

<body>
    <h1>Let's do some LeaderLine testing!</h1>

    <span id="start" style="margin-right: 100px;">start</span>
    <span id="end">end</span>

    <div class="nodes-container">
        <p id="node1" class="node">Climate Change</p>
        <p id="node2" class="node">Evidence</p>
        <p id="node3" class="node">Causes</p>
        <p id="node4" class="node">Solutions</p>
        <p id="node5" class="node">Further research</p>
        <p id="node6" class="node">change human behavior</p>
        <p id="node7" class="node">human activities</p>
        <p id="node8" class="node">warming oceans</p>
    </div>
</body>

<script src="{% static 'leader-line.min.js' %}"></script>
<script src="{% static 'lines.js' %}"></script>

</html>